"""CLI for explicit scans, local serving, bounded observation and approvals.

Examples live in this experiment's README. This entry point never installs a
scheduler or starts an existing forward pulse, and has no notification sender.
"""
from __future__ import annotations

import argparse
from dataclasses import replace
import json
from pathlib import Path
import subprocess
import sys
import time

from yoyo.contracts.rotation import (EXPERIMENT, EXPERIMENT_ID, ROOT, RotationError,
                                    iso, load_config, now_utc, source_identity)
from yoyo.rotation.journal import Journal
from yoyo.rotation.metadata import load_catalog
from yoyo.rotation.server import Observer, candidate_csv, create_app


def frozen_sources(config_path: Path = EXPERIMENT / "config.json") -> str:
    """Real builds require all observer sources/config/catalog committed first."""
    paths = list(source_identity()["files"])
    paths += [str((EXPERIMENT / name).relative_to(ROOT)) for name in ("config.json", "event_catalog.json", "PROJECT_PLAN.md")]
    try:
        paths.append(str(config_path.resolve().relative_to(ROOT)))
    except ValueError as exc:
        raise RotationError("real observation configuration must be committed inside this repository") from exc
    for rel in paths:
        result = subprocess.run(["git", "show", "HEAD:" + rel], cwd=ROOT, capture_output=True)
        if result.returncode or result.stdout != (ROOT / rel).read_bytes():
            raise RotationError("commit observer builder before real acquisition: " + rel)
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Fable selective-altcoin research observer")
    parser.add_argument("command", choices=["scan", "serve", "watch", "status", "approval-request", "export"])
    parser.add_argument("--config", type=Path, default=EXPERIMENT / "config.json")
    parser.add_argument("--receipt", type=Path, help="actual owner approval receipt; never generated by this tool")
    parser.add_argument("--runtime", type=Path, default=EXPERIMENT / "runtime")
    parser.add_argument("--synthetic", action="store_true", help="explicitly use synthetic engineering scenarios")
    parser.add_argument("--port", type=int, default=18766)
    parser.add_argument("--cycles", type=int, default=1, help="bounded explicit watch iterations, 1..96")
    args = parser.parse_args(argv)
    try:
        config = load_config(args.config)
        if args.synthetic:
            config = replace(config, mode="synthetic_demo", universe_mode="explicit")
        identity = source_identity()
        if args.command == "approval-request":
            live = replace(config, mode="live_observation", as_of="live", universe_mode="exchange_spot")
            print(json.dumps({"status": "not_approved", "experiment_id": EXPERIMENT_ID,
                  "scope": "bounded_live_observation", "proposed_config": live.to_dict(),
                  "config_hash": live.config_hash, **identity,
                  "requested_authorization": "Approve this unchanged configuration's current-market observations with a stated expiry and holdout consumption number; no trading, training, deployment or messages.",
                  "receipt_required_fields": ["experiment_id", "scope", "config_hash", "source_hash", "owner_quote", "reference", "approved_at", "valid_until", "consumption_number"]}, ensure_ascii=False, indent=2))
            return 0
        receipt = json.loads(args.receipt.read_text()) if args.receipt else None
        catalog = load_catalog(EXPERIMENT / "event_catalog.json")
        def scan_function(configuration, **kwargs):
            from yoyo.rotation.pipeline import run_scan
            if configuration.mode != "synthetic_demo" and load_config(args.config) != configuration:
                raise RotationError("configuration file changed; restart with the committed configuration")
            commit = frozen_sources(args.config) if configuration.mode != "synthetic_demo" else None
            result = run_scan(configuration, **kwargs)
            result["generator_commit"] = commit
            return result
        observer = Observer(config, journal=Journal(args.runtime), catalog=catalog, receipt=receipt,
                            scan_function=scan_function, catalog_path=EXPERIMENT / "event_catalog.json")
        if args.command == "serve":
            if not 1024 <= args.port <= 65535:
                raise RotationError("port must be between 1024 and 65535")
            import uvicorn
            uvicorn.run(create_app(observer), host="127.0.0.1", port=args.port, log_level="warning")
            return 0
        if args.command == "status":
            print(json.dumps({"config": config.to_dict(), "policy": observer.policy(), **identity}, ensure_ascii=False, indent=2))
            return 0
        if args.command == "export":
            sys.stdout.write(candidate_csv(observer.latest()))
            return 0
        if not 1 <= args.cycles <= 96:
            raise RotationError("cycles must be 1..96")
        if args.command == "watch" and config.mode != "live_observation":
            raise RotationError("watch requires a specifically approved live-observation configuration")
        cycles = args.cycles if args.command == "watch" else 1
        for i in range(cycles):
            snapshot = observer.scan()
            print(json.dumps({"scan_id": snapshot["scan_id"], "mode": snapshot["mode"],
                              "as_of": snapshot["as_of"], "status": snapshot["status"],
                              "coverage": snapshot["universe"], "regime": snapshot["regime"]["state"],
                              "candidates": len(snapshot["candidates"]), "duration_seconds": snapshot["duration_seconds"],
                              "journal": str(observer.journal.path)}, ensure_ascii=False), flush=True)
            if i + 1 < cycles:
                # A deliberately explicit command, never an installed background task.
                time.sleep(config.observation_interval_seconds)
        return 0
    except (ValueError, OSError, RuntimeError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
